// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkqxb-zPkkPMiusqIY-KCfiUz8KP2PtAc',
    appId: '1:333508728729:web:bdba0d31176551f4566508',
    messagingSenderId: '333508728729',
    projectId: 'notification-qsport',
    authDomain: 'notification-qsport.firebaseapp.com',
    storageBucket: 'notification-qsport.firebasestorage.app',
    measurementId: 'G-4LJ0K7S5NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgNQEpQ-M-clZhEgeftur8OW-mhuxj4Zo',
    appId: '1:333508728729:android:e0a7d7947b1fd1aa566508',
    messagingSenderId: '333508728729',
    projectId: 'notification-qsport',
    storageBucket: 'notification-qsport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpiDMbOyD-0XM75JWkqGzLwKZjXRsZXkY',
    appId: '1:333508728729:ios:a0c8d871af58957b566508',
    messagingSenderId: '333508728729',
    projectId: 'notification-qsport',
    storageBucket: 'notification-qsport.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpiDMbOyD-0XM75JWkqGzLwKZjXRsZXkY',
    appId: '1:333508728729:ios:a0c8d871af58957b566508',
    messagingSenderId: '333508728729',
    projectId: 'notification-qsport',
    storageBucket: 'notification-qsport.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkqxb-zPkkPMiusqIY-KCfiUz8KP2PtAc',
    appId: '1:333508728729:web:92729bbfeca5838f566508',
    messagingSenderId: '333508728729',
    projectId: 'notification-qsport',
    authDomain: 'notification-qsport.firebaseapp.com',
    storageBucket: 'notification-qsport.firebasestorage.app',
    measurementId: 'G-V3RSWDTFPB',
  );
}
