name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "production", "release/*" ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'face-service/**'
      - 'mysql/**'
      - 'nginx/**'
      - 'docker-compose.yml'
  pull_request:
    branches: [ "main", "production", "release/*" ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'face-service/**'
      - 'mysql/**'
      - 'nginx/**'
      - 'docker-compose.yml'

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer, phpunit
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
        
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Run Linting (Pint)
      run: ./vendor/bin/pint --test
      continue-on-error: true
      
    - name: Run PHPUnit
      run: php artisan test --env=testing

